sudo: required
services:
  - docker

before_install:
  - docker build -t harishnarayanan/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run harishnarayanan/complex npm test -- --coverage

after_success:
  - docker build -t harishnarayanan/multi-client  ./client
  - docker build -t harishnarayanan/multi-nginx  ./nginx
  - docker build -t harishnarayanan/multi-server  ./server
  - docker build -t harishnarayanan/multi-worker  ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harishnarayanan/multi-client
  - docker push harishnarayanan/multi-nginx
  - docker push harishnarayanan/multi-server
  - docker push harishnarayanan/multi-worker

