sudo: required
services:
  - docker

before_install:
  - docker build -t harishnarayanan/complex -f ./client/Dockerfile.dev .

script:
  - docker run harishnarayanan/complex npm test -- --coverage

after_success:
  - docker build -t harishnarayanan/multi-client -f ./client
  - docker build -t harishnarayanan/multi-nginx -f ./nginx
  - docker build -t harishnarayanan/multi-server -f ./server
  - docker build -t harishnarayanan/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harishnarayanan/multi-client
  - docker push harishnarayanan/multi-nginx
  - docker push harishnarayanan/multi-server
  - docker push harishnarayanan/multi-worker
